module.exports =  {
  es6:"/images/post/es6.jpg",
  JavaScript:"/images/post/JavaScript.jpg",
  TypeScript:"/images/post/TypeScript.jpg",
  css:"/images/post/css.jpg",
  node:"/images/post/nodejs.jpg",
  vue:"/images/post/vue.jpg",
  webpack:"/images/post/webpack.jpg",
  git:"/images/post/git.jpg",
  java:"/images/post/java.jpg",
  echarts:"/images/post/echarts.jpg",
  微信小程序:"/images/post/wechat_applet.jpg",
  浏览器:"/images/post/browser.jpg",
  算法:"/images/post/algorithm.jpg",
  数据结构:"/images/post/data.jpg",
  工具:"/images/post/editor.jpg",
  UI库:"/images/post/ui.jpg",
  美化:"/images/post/beautify.jpg"
}
