avatar: /images/head/head.jpg # 网站 Logo
background: # 既是博客的背景，又是文章默认头图
  path: /images/background/xiaomai.jpg
  character: /images/background/lihui.png
  width: 1440
  height: 350
  autoCoverWidth: 1200
  autoCoverHeight: 320
favicon:
  href: /images/head/head.jpg # 网站图标
  type: image/png # 图标类型，可能的值有(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # 功能开关，可选值（true,false）
  globalToc: false # 开启该功能会自动开启文章 TOC（文章目录） 功能
  goTop: true # 是否显示回到顶部开关
  copy: false

# 附加图标库 用于自定义字体 www.iconfont.cn 登录->创建项目->添加图标->获取链接
iconlib: //at.alicdn.com/t/font_2421060_8z08qcz5sq3.css # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

searchType: local   #可选 local本地 web 网址
search: https://www.google.com/search?q= # https://www.google.com/search?q={你的博客链接}  #当searchType为web时可用

cdn: # 这里可以修改站点使用的库的CDN
  disqusjs:
    css: https://unpkg.com/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://unpkg.com/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://unpkg.com/gitalk@1.5.0/dist/gitalk.min.css
    js: https://unpkg.com/gitalk@1.5.0/dist/gitalk.min.js
  valine:
    js: https://lib.baomitu.com/valine/1.3.9/Valine.min.js
  copy: https://cdn.jsdelivr.net/gh/xtaodada/xtaodada.github.io@0.0.2/copy.js
menu:
  回到首页:
    - /
    - icon-meishi
  文章归档:
    - /archives.html
    - icon-hanbao1
  关于糖糖:
    - /about.html
    - icon-jiubei1
  我的朋友:
    - /friend.html
    - icon-cola
  下载中心:
    - /download.html
    - icon-tangguo
# 侧边模块
widgets:
- search
- social
- category
- tagcloud
- archive #: widgetAchive
#- recent_posts
# - link #settings: widgetLink

maxTagcloud: 0  # 0 表示不限制

social:
  QQ:
    - http://wpa.qq.com/msgrd?v=3&uin=2120252100&site=qq&menu=yes
    - icon-QQ
    - rgb(64, 196, 255)
    - rgba(64, 196, 255, .1)
  mail:
    - mailto:tangyuxian@vip.qq.com
    - icon-mail-fill
    - rgb(249,8,8)
    - rgba(249,8,8,.1)
  CSDN:
    - https://blog.csdn.net/qq_40621378?type=blog
    - icon-csdn
    - rgb(199,29,35)
    - rgba(199,29,35,.1)
  博客园:
    - https://www.cnblogs.com/lovetangyuxian/
    - icon-bokeyuan
    - rgb(66, 214, 29)
    - rgba(66, 214, 29, .1)
  GitHub:
    - https://github.com/tangyuxian/
    - icon-github
    - rgb(25, 23, 23)
    - rgba(25, 23, 23, .15)
  gitee:
    - https://gitee.com/tangyuxian
    - icon-mayun
    - rgb(255, 255, 255)
    - rgb(199,29,35)


site_verification: # 向搜索引擎验证你对站点的所有权，用于向搜索引擎提交 sitemap 和管理站点被搜索引擎收录的情况。
  google:
  baidu: code-J1Qg17G6wT

analytics: # 统计系统，目前支持 Google analytics.js 统计、Google Tag Manager 统计、CNZZ 统计、腾讯统计、51.La统计、百度统计
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

# 评论来源点
comment: valine # 评论框，目前支持 gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot

gitalk:
  admin:  # 拥有对该repo进行操作的 GitHub username
  owner:  # 持有该 repo 的 GitHub username
  repo:  # 存放评论的 issue 所在的 repo
  clientID:  # GitHub Client ID
  clientSecret:  # GitHub Client Secret

gitment:
  owner:  # 持有该 repo 的 GitHub username
  repo:  # 存放评论的 issue 所在的 repo
  clientID:  # GitHub Client ID
  clientSecret:  # GitHub Client Secret

valine:
  appId: r5zxC0st0DDjPA9auXzMV7HY-gzGzoHsz # leancloud application app id
  appKey: 3bqCsovpyfTPHUzTHovd3V3V # leancloud application app key

disqus:
  shortname: <shortname> # 你的 Disqus shortname

disqusjs:
  shortname: <shortname> # 你的 Disqus shortname
  sitename: <sitename> # 你站点的名称，将会显示在「评论基础模式」的 header 中；该配置应该和 Disqus Admin - Settings - General - Website Name 一致
  api: https://disqus.skk.moe/disqus/ # DisqusJS 请求的 API Endpoint，通常情况下你应该配置一个 Disqus API 的反代并填入反代的地址。你也可以直接使用 DISQUS 官方 API 的 Endpoint https://disqus.com/api/，或是使用SukkaW搭建的 Disqus API 反代 Endpoint https://disqus.skk.moe/disqus/。
  apikey: <api_key> # DisqusJS 向 API 发起请求时使用的 API Key，你应该在配置 Disqus Application 时获取了 API Key;DisqusJS 支持填入一个 包含多个 API Key 的 Array，在每次请求时会随机使用其中一个；如果你只需要填入一个 API Key，则可以填入 String 或 Array。
  admin: <admin> # 你的站点的 Disqus Moderator 的用户名（也就是你的用户名）。你可以在 Disqus - Settings - Account - Username 获取你的 Username
  adminLabel: <adminLabel> # 你想显示在 Disqus Moderator Badge 中的文字。该配置应和 Disqus Admin - Settings - Community - Moderator Badge Text 相同

changyan:
  appid: <APP_ID> # 畅言的 APPID
  conf: <CONF> # 畅言的 CONF
  thread_key_type: path # 可选 id 或 path

livere:
  data_uid: <data_uid> # 你的来必力 UID，可以在来必力后台获取

DiscussBot:
  id: <id> # 站点id
  comments: 5 # 可能是限制每位用户单页面评论最多条数？
  color: # 评论框主色调
  dislike: 0 # 显示差评按钮
  icons: 0 # 图标主题
  diff: 0 # 每位用户name不同颜色

# 文章的版权声明
copyright: '<strong>版权声明：</strong>本文采用 <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> 协议进行许可'

#achive widget behavior
widgetAchive: #文章归档组件
  archive_type: 'year' #按月展示还是按年展示
  show_count: true  #是否展示数量

widgetLink: #链接组件
  - title: <title>
    img : <img_path>
    link : <url>
  - title: <title>
    img : <img_path>
    link : <url>
sidebar: ''
beian: '辽ICP备2021002341号'
#  --------小埋主题 追加配置
# Online daovoice 即时通讯插件(请到 http://dashboard.daovoice.io/ 申请key)
daovoice:
  enable: true  #是否启用
  app_id: 250cb4aa
# 不蒜子访客统计
busuanzi: true
# 扩展挂件
pendants:
  - clock #时钟
  - qweather #天气(需要配置具体参数)

# qweather配置项(请到 https://www.qweather.com/ 申请key)
qweather:
  layout: 2
  width: 260
  height: 220
  background: 5
  dataColor: e67249
  borderRadius: 15
  key: f74d1e1690e6432d801e97fa2f05a162

