continue: More
nav:
  home: Home

search: Search
archive: Archive
recent_posts: Recent Posts
categories: Categories
hitokoto: Hitokoto
tagcloud: Tagcloud
social: Social

count:
  articles: Articles
  tags: Tags
  categories: Categories
  
copyright:
  author: Author
  permalink: Link
  from: From
memos:
  loading: Loading...
  more: Load More
  no_dynamic: No Dynamic
  loading_failed: Loading Failed
  retry: Retry
  just_now: Now Now
  yesterday: Yesterday
  minutes_ago: Minutes Ago
  hours_ago: Hours Ago
  days_ago: Days Ago